- hosts: 3.145.211.239
  become: yes
  become_method: sudo
  gather_facts: true
  vars:
    jboss_eap_user: jboss-eap
    jboss_eap_group: jboss-eap
    eap_deploy_dir: /opt
    eap_version: 7.4
    eap_archive: /home/imss/jboss-eap-7.4.0.zip
    eap_home: "{{ eap_deploy_dir }}/jboss-eap-{{eap_version}}"
    rhel_initd: /etc/init.d
    jboss_eap_service_conf_dir: "/etc/default"
  tasks:
    - name: Install JBoss Requirements
      dnf:
        name: java-1.8.0-openjdk-devel, unzip, initscripts
        state: present

    - name: Check if Service Exists
      stat: path=/etc/init.d/jboss-eap-rhel.sh
      register: service_status

    - name: Ensure EAP service is stopped
      when: service_status.stat.exists
      ignore_errors: yes
      service:
        name: jboss-eap-rhel
        state: stopped

    - name: Create JBoss EAP Group
      group:
        name: "{{ jboss_eap_group }}"
        system: yes
        state: present
        gid: "{{ jboss_eap_group_gid | default('400') }}"

    - name: Create JBoss EAP User
      user:
        name: "{{ jboss_eap_user }}"
        comment: "JBoss EAP User"
        uid: "{{ jboss_eap_user_uid | default('400') }}"
        group: "{{ jboss_eap_group }}"
        home: "{{ eap_deploy_dir }}"

    - name: Clean EAP directory
      file:
        state: absent
        path: "{{ eap_home }}/"

    - name: Unarchive EAP
      unarchive:
        src: "{{ eap_archive }}"
        dest: "{{ eap_deploy_dir }}"
        owner: "{{ jboss_eap_user }}"
        group: "{{ jboss_eap_group }}"

    - name: Create symlink
      file:
        src: "{{eap_home}}"
        dest: "/opt/jboss-eap"
        state: link

    - name: Modify JBoss EAP Configuration File
      lineinfile:
        state: present
        path: "{{ eap_home }}/bin/init.d/jboss-eap.conf"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - {regexp: "^# JBOSS_USER=", line: "JBOSS_USER=jboss-eap"}
        - {regexp: "^# JBOSS_CONFIG=", line: "JBOSS_CONFIG=standalone-ha.xml"}
        - {regexp: "^# JBOSS_OPTS=", line: "JBOSS_OPTS=\"-b 0.0.0.0\""}

    - name: Copy JBoss Service Configuration File
      copy:
        src: "{{ eap_home }}/bin/init.d/jboss-eap.conf"
        dest: "{{ jboss_eap_service_conf_dir }}/"
        remote_src: True
        owner: "{{ jboss_eap_user }}"
        group: "{{ jboss_eap_group }}"

    - name: Copy JBoss EAP Service File
      copy:
        src: "{{ eap_home }}/bin/init.d/jboss-eap-rhel.sh"
        dest: "{{ rhel_initd }}"
        remote_src: True
        owner: "{{ jboss_eap_user }}"
        group: "{{ jboss_eap_group }}"
        mode: 0755

    - name: Enable EAP service
      service:
        name: jboss-eap-rhel.sh
        enabled: yes

    - name: Start EAP service
      service:
        name: jboss-eap-rhel
        state: started
